defaultLocale: nl
partners:
  - name: Frank Verstegen
    address: |
      Wildbaan 8
      4386 GE Vlissingen
    email: frankverstegen@barnsby.nl
    phone: 31(0) 638532614
  - name: Jan-Willem van Riet
    address: |
      Tiendweg 22
      2871AC Schoonhoven
    email: janwillemvanriet@barnsby.nl
    phone: +31 (0) 6 10118549
